### PR TITLE
Fixed footer icons new tab and spacing issue

### LINKED ISSUE #127: Update Footer
image

- Adjust the non-mobile spacing to look more like the figma
- Have the links (insta, discord, linkedin) open to a new tab when clicked (target="_blank")

### PR DESCRIPTION
**Pull request by agoel27**
1600px monitor
Screenshot 2024-09-03 at 2 39 24 PM

Large Laptop
Screenshot 2024-09-03 at 2 39 35 PM

Laptop
Screenshot 2024-09-03 at 2 39 45 PM

Tablet
Screenshot 2024-09-03 at 2 39 53 PM

- Fixed footer spacing to make it look more like figma
- Footer icons open links in new tab
- Closes #127

### CODE REVIEW

File: src/components/Footer.jsx [hunk 1]
```diff
@@ -14,20 +14,32 @@ const Footer = () => {
...
+            target="_blank"
+            className=""
+          >
             <FaInstagram className="filter invert size-8" />
           </Link>
-          <Link href="https://www.linkedin.com/company/ai-at-ucr/" className="">
+          <Link
+            href="https://www.linkedin.com/company/ai-at-ucr/"
+            target="_blank"
+            className=""
```
Comment (khandrew1) [inline src/components/Footer.jsx]: remove blank class names

**Review by khandrew1 — CHANGES_REQUESTED** [review]

**Review by khandrew1 — APPROVED** [review]
